const routeNames = {
  superAdmin: {
    dashboard: "/",
    addNgo: "/add-ngo",
    addProject: "/add-project",
    viewProject: "/view-projects",
    viewNgo: "/view-ngos",
    addBranch: "/add-branch",
    viewBranches: "/view-branches",
    addUserType: "/add-user-type",
    viewUserType: "/view-userTypes",
    addUser: "/add-user",
    addUserVerification: "/add-user-verification",
    verificationSchedule: "/user-verificaiton-schedule",
    userVerification: "/user-verification/:id",
    viewUser: "/view-users",
    chats: "/chat",
    complaints: "/complaints",
    reviews: "/reviews",
    addDocument: "/add-document",
    viewDocuments: "/view-documents",
    viewPayments: "/view-payments",
    settings: "/settings",
    addAppoinment: "/add-appointment",
    viewAppoinments: "/view-appointments",
    startAppoinment: "/start-appointment",
    missingDocuments: "/missing-documents",
    appointmentSchedule: "/appointment-schedule",
    addRoaster: "/add-roaster",
    viewRoasters: "/view-roasters",
    viewAppoinment: "/view-appointment",
    editAppoinment: "/edit-appointment",
    schedule: "/schedule",
    connect: "/connect",
  },
};

export default routeNames;
